name: pharmapos_new
description: A modern pharmacy point of sale system built with Flutter for desktop and mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Database - Works offline
  sqflite_common_ffi: ^2.3.0  # For desktop
  sqflite: ^2.3.0  # For mobile
  path: ^1.8.3

  # Core utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  uuid: ^4.1.0

  # PDF and sharing - offline capable
  pdf: ^3.10.7
  printing: ^5.11.0
  share_plus: ^7.2.1

  # Desktop window management
  window_manager: ^0.3.7
  desktop_window: ^0.4.0

  # File operations - offline
  file_picker: ^10.2.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets - All stored locally for offline use
  assets:
    - assets/images/
    - assets/fonts/

  # System fonts for better compatibility
  # Custom fonts commented out to reduce APK size and ensure offline functionality
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700